### ISSUE TITLE
Enalrgment duration

### ISSUE THREAD

**Issue by Lija321** [mechtifs/wiggle#9]
the implementation seems to be broken in my testing, which makes the mouse unusable. also, the prefs page is no longer working due to a missing comma.
sorry to revert your changes. if you can fix the above issues, welcome to open another pr :)
(or i'd re-implement it someday?)

_Originally posted by @mechtifs in https://github.com/mechtifs/wiggle/issues/5#issuecomment-2053618034_

**Comment by Lija321** [comment]
I fixed the prefs issue but can you describe what makes the mouse unusable. Im running on gnome 45 everything seems to be working

**Comment by mechtifs** [comment]
let me explain what went wrong:
because an additional delay is now set manually, the variable `isWiggling` will also be updated after the delay.
since `unmagnify()` is now asynchronous, it will be called multiple times during the delay until `isWiggling` is set to `false` if the delay is longer than 2x check timeout.
what breaks the whole thing is the `remove_child()` function. when the child is already removed, it will panic.
perhaps the old `remove_actor()` will just ignore it, or you're just using a delay value that is lower than 2x check timeout. but overall that definitely **is** problematic.

also i'd like to mention that the delay will not be an exact value. in order to achieve better performance, wiggle checks every 200ms by default.
therefore, the actual delay will sit around [delay, delay+200ms]. to achieve better accuracy, the check timeout should be set to a lower value.

anyway, thanks for your suggestion :)
